{"uid": C:\Users\amal\Google Drive\Projet Business Process\project\R1\acceptance\BU_0.bnf
"res":[{ http :// example .com / customerFile :001}]
"ext-op": [{
    "name":verification ,
    " rel ": [{
      "type ": precedes,
      "op": [{
          " name ":  acceptance }]
}]
}]
}