{"uid": C:\Users\amal\Google Drive\Projet Business Process\project\R1\opening\BU_Obl0.bnf
"res":[{ http :// example .com / customerFile :001}]
"ext-op": [{
    "name":creation ,
    " rel ": [{
      "type ": precedes,
      "op": [{
          " name ":  opening }]
}]
}]
}