{"uid": C:\Users\amal\Google Drive\Projet Business Process\project\R1\closure\BU_0.bnf
"res":[{ http :// example .com / customerFile :001}]
"ext-op": [{
    "name":archive ,
    " rel ": [{
      "type ": precedes,
      "op": [{
          " name ":  closure }]
}]
}]
}